---
title: "Structural Equation Model"
author: "Jinbo Niu"
date: "2023/6/6"
output:
  html_document: default
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(lavaan)
library(semPlot)
```
## Data Loading
The dataset is about the democracy situation of developed countries. The dataset contains several 

```{R}
data("PoliticalDemocracy")
str(PoliticalDemocracy)
```
## Model Construction

```{r}
model <- '#测量模型
          ind60 =~ x1+x2+x3
          dem60 =~y1+y2+y3+y4
          dem65=~y5+y6+y7+y8
          
          #regression
          dem60~ind60
          dem65~ind60+dem60
          
          #residual
          y1~~y5
          y2~~y4+y6
          y3~~y7
          y4~~y8
          y6~~y8'
```

```{r}
fit <- sem(model,data = PoliticalDemocracy)
summary(fit,standardized = TRUE)
```
## Assessment  of the model
The model will be assessed by indicators including CHISQ(p>0.05), GFI(>0.9), CFI(>0.95), RMR(as little as possible),
SRMR(<0.08), RMSEA(<0.05). 
```{r}
fitmeasures(fit,c("chisq","df","pvalue","gfi","cfi","rmr","srmr","rmsea"))
```
## Visualize the model
```{r}
semPaths(fit,what = "std",layout = "tree2",fade = FALSE,residuals = FALSE, nCharNodes = 0)
        
```
