---
title: "Text Mining"
author: "Jinbo Niu"
date: "2023/3/18"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
library(tidytext,quietly = TRUE)
library(dplyr,quietly = TRUE)

```

```{r}
text <- c("Because I could not stop for death - ",
          "He kindly stopped for me-",
          "The carriage held but just Ourselves",
          "and Immortality")

text_df <- data.frame(line = 1:4,text = text)
text_df %>% unnest_tokens(word,text)
```

## Jane Austen's work
```{r}
library(janeaustenr)
library(stringr)
```

```{r}
original_books <- austen_books()%>% 
  group_by(book) %>% 
  mutate(linenumber = row_number(),chapter = cumsum(str_detect(text,regex("^chapter [\\divxlc]",ignore_case = TRUE)))) %>% ungroup()

  original_books
```

```{r}
tidy_books <- original_books %>%
  unnest_tokens(word,text)

tidy_books
```

```{R}
data("stop_words")
tidy_books <- tidy_books %>% anti_join(stop_words)

tidy_books %>% count(word,sort = TRUE)
```

```{R}
library(ggplot2)
```

```{R}
tidy_books %>% 
  count(word,sort = TRUE)%>%
  filter(n>600) %>%
  mutate(word = reorder(word,n))%>%
  ggplot(aes(word,n))+geom_col()+xlab(NULL)+coord_flip()
```
## Jane Austen's work with other works

### H.G.Wells work
```{r}
library(gutenbergr)
hgwells <- gutenberg_download(c(35,36,5230,159))
```

```{r}
tidy_hgwells <- hgwells %>% unnest_tokens(word,text)%>%anti_join(stop_words)

#most frequent words used by Wells
tidy_hgwells %>% count(word,sort = TRUE)

```

### Bronte's work
```{r}
bronte <- gutenberg_download(c(1260,768,969,9182,767))
```

```{r}
tidy_bronte <- bronte%>%unnest_tokens(word,text)%>%anti_join(stop_words)
tidy_bronte %>% count(word,sort = TRUE)
```

```{r}
library(tidyr)
frequency <- bind_rows(mutate(tidy_bronte,author = "Bronte Sisters"),mutate(tidy_hgwells,author = "H.G.Wells"),mutate(tidy_books,author = "Jane Austen"))%>%
  mutate(word = str_extract(word,"[a-z']+"))%>%
  count(author,word) %>% group_by(author)%>%
  mutate(proportion = n/sum(n))%>%
  select(-n)%>%
  spread(author,proportion)%>%
  gather(author,proportion,`Bronte Sisters`:`H.G.Wells`)

frequency 
``` 

#Visualize the data
```{r}
library(scales)
ggplot(frequency,aes(x = proportion,y = `Jane Austen`,color = abs(`Jane Austen`-proportion)))+
  geom_abline(color = "gray40",lty = 2)+
  geom_jitter(alpha = 0.1,size = 2.5,width = .3, height = .3)+
  geom_text(aes(label = word),check_overlap = TRUE,vjust = 1.5)+
  scale_x_log10(labels = percent_format())+
  scale_y_log10(labels = percent_format())+
  scale_color_gradient(limits = c(0,0.001),low = "darkslategray4",high = "gray75")+
  facet_wrap(~author,ncol = 2)+theme(legend.position = "none")+labs(y = "Jane Austen", x = NULL)

```

#Compare the correlation of frequency between three authors
```{r}
cor.test(data = frequency[frequency$author == "Bronte Sisters",],~proportion+`Jane Austen`)
cor.test(data = frequency[frequency$author == "H.G.Wells",],~proportion+`Jane Austen`)
```


